[package]
name = "currencylib"
version = "0.1.0"
edition = "2024"
authors = ["Muhammad Fathir Irhas <fathir.irhas@gmail.com>"]
description = "A library containing types and metadata for currencies."
license = "MIT"
repository = "https://github.com/mfirhas/currencylib"
documentation = "https://docs.rs/currencylib"
keywords = ["finance", "currency", "money", "type-safe", "no-std"]
categories = ["finance", "data-structures"]

[dependencies]

[build-dependencies]
iso_currency = { version = "0.5.3", features = ["iterator"] }
phf = { version = "0.13", features = ["macros"] }
